name: deploy page

on:
  push:
    branches:
      - master
      - add-page

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Yarn Install
        run: yarn install
      
      - name: Build (Generate)
        run: yarn generate

      - name: Settings and Deploy
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git clone https://x-access-token:${ACCESS_TOKEN}@github.com/jellyfish26/competitive-library.git
          cd ./competitive-library
          git switch gh-pages
          rm * -r
          cp ../dist/* . -r
          git add --all
          git config user.name "jellyfish26"
          git config user.email "jellyfish0162@gmail.com"
          git commit -m "Pages Update!"
          git push https://x-access-token:${ACCESS_TOKEN}@github.com/jellyfish26/competitive-library.git gh-pages
          

          


